GET http://localhost:3000

###

POST http://localhost:3000/signin
Content-Type: application/json

{
    "email": "eddy@gmail.com",
    "password": "hello"
}

###

POST http://localhost:3000/register
Content-Type: application/json

{
    "email": "eddy@gmail.com",
    "password": "hello",
    "name": "Eddy"
}

###

POST http://localhost:3000/register
Content-Type: application/json

{
    "email": "john@gmail.com",
    "password": "cookies",
    "name": "John"
}

###

GET http://localhost:3000/profile/123

###

PUT http://localhost:3000/image
Content-Type: application/json

{
    "id": 1
}

###

GET http://localhost:3000/profile/1
